# Generated by Django 3.0.6 on 2020-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20201028_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
