# Generated by Django 3.0.6 on 2020-11-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
