# Generated by Django 3.0.6 on 2020-11-22 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_user_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='liked',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
