# Generated by Django 3.1.3 on 2020-11-28 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_comment_commentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
