# Generated by Django 3.1.3 on 2020-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20201128_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='picture',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
